export const LOGOUT = 'LOGOUT'

//whitelist
export const DELETE_WHITELIST_RECORD = 'DELETE_WHITELIST_RECORD'
export const APPROVE_WHITELIST_RECORD = 'APPROVE_WHITELIST_RECORD'
export const CONFIRM_FOR_DELETE_WHITELIST_BATCH_FILE = 'CONFIRM_FOR_DELETE_WHITELIST_BATCH_FILE'
export const APPROVE_WHITELIST_BATCH_FILE = 'APPROVE_WHITELIST_BATCH_FILE'
export const SUBMIT_FOR_APPROVE_WHITELIST_BATCH_FILE = 'SUBMIT_FOR_APPROVE_WHITELIST_BATCH_FILE'
export const RETURN_WHITELIST_BATCH_FILE = 'RETURN_WHITELIST_BATCH_FILE'
export const CREATE_WHITELIST_RECORD = 'CREATE_WHITELIST_RECORD'
export const REJECT_WHITELIST_RECORD = 'REJECT_WHITELIST_RECORD'
export const RETURN_WHITELIST_RECORD = 'RETURN_WHITELIST_RECORD'
export const SUBMIT_FOR_DELETION_WHITELIST_RECORD = 'SUBMIT_FOR_DELETION_WHITELIST_RECORD'
export const REJECT_REQUEST_WHITELIST_BATCH_FILE = 'REJECT_REQUEST_WHITELIST_BATCH_FILE'


//system user
export const DELETE_SYSTEM_USER = 'DELETE_SYSTEM_USER'
export const RESET_PASSWORD_SYSTEM_USER = 'RESET_PASSWORD_SYSTEM_USER'
export const CHANGE_PRODUCT_STATUS = 'CHANGE_PRODUCT_STATUS'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const CONFIRM_CONTACT_US = 'CONFIRM_CONTACT_US'
export const CONFIRM_UPDATE_VERSION = 'CONFIRM_UPDATE_VERSION'
export const CONFIRM_OTHERS_UPDATE = 'CONFIRM_OTHERS_UPDATE'
export const CONFIRM_APP_MAINTENANCE = 'CONFIRM_APP_MAINTENANCE'
export const CONFIRM_SUPEND_CUSTOMER = 'CONFIRM_SUPEND_CUSTOMER'
export const CONFIRM_RESET_CUSTOMER_PASSWORD = 'CONFIRM_RESET_CUSTOMER_PASSWORD'
export const DELETE_ASSESSMENT_LCY = 'DELETE_ASSESSMENT_LCY'
export const CLOSE_TICKET = 'CLOSE_TICKET'




// Dùng để gọi lại API khi CRUD
export const REFETCH_QUERIES = 'REFETCH_QUERIES'