name: frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  drag_and_drop_lists: ^0.3.3
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_reorderable_list: ^1.3.1
  flutter_staggered_animations: ^1.1.1
  http: ^1.2.1
  intl: ^0.18.1
  sqflite: ^2.3.3
  tiengviet: ^1.0.0
  api_cache_manager: ^1.0.1
  snippet_coder_utils: ^1.0.15
  google_sign_in: ^6.2.1
  firebase_auth: ^4.19.1
  provider: ^6.1.2
  firebase_core: ^2.29.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  image_picker: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  shimmer: ^3.0.0
  awesome_notifications: ^0.8.2
  firebase_messaging: ^14.9.2
  device_info_plus: ^10.1.0
  uuid: ^4.4.0
  photo_view: ^0.15.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/i16/
    - assets/icons/fruits/
    - assets/icons/meats/
    - assets/icons/vegetables/
    - assets/icons/seafood/
    - assets/icons/dairy_products/
    - assets/icons/dishes/
    - assets/icons/drinks/
    - assets/icons/alcohol/
    - assets/icons/sauces/
    - assets/icons/spices/
    - assets/icons/bread/
    - assets/icons/desserts/
    - assets/icons/nuts/
    - assets/icons/cereals/
    - assets/icons/etc/
