import 'package:frontend/types/food.dart';
import 'package:frontend/types/type.dart';

List<Category> fruits = [
  Category(
    label: 'Táo',
    value: 'tao',
    icon: 'assets/icons/fruits/tao.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cam',
    value: 'cam',
    icon: 'assets/icons/fruits/cam.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Dâu tây',
    value: 'dau-tay',
    icon: 'assets/icons/fruits/dau-tay.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Chuối',
    value: 'chuoi',
    icon: 'assets/icons/fruits/chuoi.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Đu đủ',
    value: 'du-du',
    icon: 'assets/icons/fruits/du-du.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Đào',
    value: 'dao',
    icon: 'assets/icons/fruits/dao.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Ô liu',
    value: 'o-liu',
    icon: 'assets/icons/fruits/o-liu.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Vải',
    value: 'vai',
    icon: 'assets/icons/fruits/vai.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Việt quất',
    value: 'viet-quat',
    icon: 'assets/icons/fruits/viet-quat.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Táo xanh',
    value: 'tao-xanh',
    icon: 'assets/icons/fruits/tao-xanh.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Táo tàu',
    value: 'tao-tau',
    icon: 'assets/icons/fruits/tao-tau.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Khế',
    value: 'khe',
    icon: 'assets/icons/fruits/khe.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Sầu riêng',
    value: 'sau-rieng',
    icon: 'assets/icons/fruits/sau-rieng.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Lựu',
    value: 'luu',
    icon: 'assets/icons/fruits/luu.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Xoài',
    value: 'xoai',
    icon: 'assets/icons/fruits/xoai.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Ổi',
    value: 'oi',
    icon: 'assets/icons/fruits/oi.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Chôm chôm',
    value: 'chom-chom',
    icon: 'assets/icons/fruits/chom-chom.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bơ',
    value: 'bo',
    icon: 'assets/icons/fruits/bo.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Thanh long',
    value: 'thanh-long',
    icon: 'assets/icons/fruits/thanh-long.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Sung',
    value: 'sung',
    icon: 'assets/icons/fruits/sung.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nho tím',
    value: 'nho-tim',
    icon: 'assets/icons/fruits/nho-tim.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Mọng',
    value: 'mong',
    icon: 'assets/icons/fruits/mong.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Mơ',
    value: 'mo',
    icon: 'assets/icons/fruits/mo.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Măng cụt',
    value: 'mang-cut',
    icon: 'assets/icons/fruits/mang-cut.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Kiwi',
    value: 'kiwi',
    icon: 'assets/icons/fruits/kiwi.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hồng',
    value: 'hong',
    icon: 'assets/icons/fruits/hong.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Dứa',
    value: 'dua',
    icon: 'assets/icons/fruits/duas.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Anh đào',
    value: 'anh-dao',
    icon: 'assets/icons/fruits/anh-dao.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Quả nho',
    value: 'quan-thoai',
    icon: 'assets/icons/fruits/quan-thoai.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Mận',
    value: 'man',
    icon: 'assets/icons/fruits/man.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Dưa vàng',
    value: 'dua-vang',
    icon: 'assets/icons/fruits/dua-vang.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Lê',
    value: 'le',
    icon: 'assets/icons/fruits/le.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nhãn',
    value: 'nhan',
    icon: 'assets/icons/fruits/nhan.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Dừa',
    value: 'dua',
    icon: 'assets/icons/fruits/duaf.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Dưa hấu',
    value: 'dua-hau',
    icon: 'assets/icons/fruits/dua-hau.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Dưa lưới',
    value: 'dua-luoi',
    icon: 'assets/icons/fruits/dua-luoi.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Quất',
    value: 'quat',
    icon: 'assets/icons/fruits/quat.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cà chua bi',
    value: 'ca-chua-bi',
    icon: 'assets/icons/fruits/ca-chua-bi.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cà chua',
    value: 'ca-chua',
    icon: 'assets/icons/fruits/ca-chua.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Chuối',
    value: 'chuoi',
    icon: 'assets/icons/fruits/chuoi.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Chanh xanh',
    value: 'chanh-xanh',
    icon: 'assets/icons/fruits/chanh-xanh.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Chanh vàng',
    value: 'chanh-vang',
    icon: 'assets/icons/fruits/chanh-vang.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bưởi',
    value: 'buoi',
    icon: 'assets/icons/fruits/buoi.png',
    type: 'fruits',
    defaultDuration: 1,
  ),
];

List<Category> vegetables = [
  Category(
    label: 'Khoai môn',
    value: 'khoai-mon',
    icon: 'assets/icons/vegetables/khoai-mon.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nấm',
    value: 'nam',
    icon: 'assets/icons/vegetables/nam.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nấm kim châm',
    value: 'nam-kim-cham',
    icon: 'assets/icons/vegetables/nam-kim-cham.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nấm hương',
    value: 'nam-huong',
    icon: 'assets/icons/vegetables/nam-huong.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Đậu que',
    value: 'dau-que',
    icon: 'assets/icons/vegetables/dau-que.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Ớt chỉ thiên',
    value: 'ot-chi-thien',
    icon: 'assets/icons/vegetables/ot-chi-thien.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Ớt chuông',
    value: 'ot-chuong',
    icon: 'assets/icons/vegetables/ot-chuong.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Tỏi tây',
    value: 'toi-tay',
    icon: 'assets/icons/vegetables/toi-tay.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Ớt',
    value: 'ot',
    icon: 'assets/icons/vegetables/ot.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Súp lơ trắng',
    value: 'sup-lo-trang',
    icon: 'assets/icons/vegetables/sup-lo-trang.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Xu hào',
    value: 'xu-hao',
    icon: 'assets/icons/vegetables/xu-hao.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bí ngô vàng',
    value: 'bi-ngo-vang',
    icon: 'assets/icons/vegetables/bi-ngo-vang.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rau diếp',
    value: 'rau-diep',
    icon: 'assets/icons/vegetables/rau-diep.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rau chân vịt',
    value: 'rau-chan-vit',
    icon: 'assets/icons/vegetables/rau-chan-vit.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cần tây',
    value: 'can-tay',
    icon: 'assets/icons/vegetables/can-tay.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Xà lách',
    value: 'xa-lach',
    icon: 'assets/icons/vegetables/xa-lach.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bí xanh',
    value: 'bi-xanh',
    icon: 'assets/icons/vegetables/bi-xanh.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nấm sò',
    value: 'nam-so',
    icon: 'assets/icons/vegetables/nam-so.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cải ngọt',
    value: 'cai-ngot',
    icon: 'assets/icons/vegetables/cai-ngot.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Lá lốt',
    value: 'la-lot',
    icon: 'assets/icons/vegetables/la-lot.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Măng tây',
    value: 'mang-tay',
    icon: 'assets/icons/vegetables/mang-tay.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Ngô',
    value: 'ngo',
    icon: 'assets/icons/vegetables/ngo.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nhân sâm',
    value: 'nhan-sam',
    icon: 'assets/icons/vegetables/nhan-sam.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Khoai tây',
    value: 'khoai-tay',
    icon: 'assets/icons/vegetables/khoai-tay.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Khoai lang',
    value: 'khoai-lang',
    icon: 'assets/icons/vegetables/khoai-lang.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nấm đùi gà',
    value: 'nam-dui-ga',
    icon: 'assets/icons/vegetables/nam-dui-ga.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hẹ',
    value: 'he',
    icon: 'assets/icons/vegetables/he.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hành lá',
    value: 'hanh-la',
    icon: 'assets/icons/vegetables/hanh-la.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Giá đỗ xanh',
    value: 'gia-do-xanh',
    icon: 'assets/icons/vegetables/gia-do-xanh.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Giá đỗ',
    value: 'gia-do',
    icon: 'assets/icons/vegetables/gia-do.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Dưa chuột',
    value: 'dua-chuot',
    icon: 'assets/icons/vegetables/dua-chuot.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Củ sen',
    value: 'cu-sen',
    icon: 'assets/icons/vegetables/cu-sen.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Củ cải đường',
    value: 'cu-cai-duong',
    icon: 'assets/icons/vegetables/cu-cai-duong.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Củ cải trắng',
    value: 'cu-cai-trang',
    icon: 'assets/icons/vegetables/cu-cai-trang.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Củ cải',
    value: 'cu-cai',
    icon: 'assets/icons/vegetables/cu-cai.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hành tây',
    value: 'hanh-tay',
    icon: 'assets/icons/vegetables/hanh-tay.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hành khô',
    value: 'hanh-kho',
    icon: 'assets/icons/vegetables/hanh-kho.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cải xoăn',
    value: 'cai-xoan',
    icon: 'assets/icons/vegetables/cai-xoan.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cải canh',
    value: 'cai-canh',
    icon: 'assets/icons/vegetables/cai-canh.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Xà lách dài',
    value: 'xa-lach-dai',
    icon: 'assets/icons/vegetables/xa-lach-dai.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cải bẹ xanh',
    value: 'cai-be-xanh',
    icon: 'assets/icons/vegetables/cai-be-xanh.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Măng',
    value: 'mang',
    icon: 'assets/icons/vegetables/mang.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bắp cải',
    value: 'bap-cai',
    icon: 'assets/icons/vegetables/bap-cai.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cải thảo',
    value: 'cai-thao',
    icon: 'assets/icons/vegetables/cai-thao.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cà rốt',
    value: 'ca-rot',
    icon: 'assets/icons/vegetables/ca-rot.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cà tím dài',
    value: 'ca-tim-dai',
    icon: 'assets/icons/vegetables/ca-tim-dai.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Củ cải tím',
    value: 'cu-cai-tim',
    icon: 'assets/icons/vegetables/cu-cai-tim.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Súp lơ',
    value: 'sup-lo',
    icon: 'assets/icons/vegetables/sup-lo.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bí ngô',
    value: 'bi-ngo',
    icon: 'assets/icons/vegetables/bi-ngo.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bí đỏ',
    value: 'bi-do',
    icon: 'assets/icons/vegetables/bi-do.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cải chíp',
    value: 'cai-chip',
    icon: 'assets/icons/vegetables/cai-chip.png',
    type: 'vegetables',
    defaultDuration: 1,
  ),
];

List<Category> meats = [
  Category(
    label: 'Bụng heo',
    value: 'bung-heo',
    icon: 'assets/icons/meats/bung-heo.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cánh gà',
    value: 'canh-ga',
    icon: 'assets/icons/meats/canh-ga.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Chân giò',
    value: 'chan-gio',
    icon: 'assets/icons/meats/chan-gio.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Đùi gà',
    value: 'dui-ga',
    icon: 'assets/icons/meats/dui-ga.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Gà',
    value: 'ga',
    icon: 'assets/icons/meats/ga.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Gà tây',
    value: 'ga-tay',
    icon: 'assets/icons/meats/ga-tay.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Giăm bông',
    value: 'giam-bong',
    icon: 'assets/icons/meats/giam-bong.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Giò tươi',
    value: 'gio-tuoi',
    icon: 'assets/icons/meats/gio-tuoi.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Jamon',
    value: 'jamon',
    icon: 'assets/icons/meats/jamon.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Mắt sườn',
    value: 'mat-suon',
    icon: 'assets/icons/meats/mat-suon.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Prosciutto',
    value: 'prosciutto',
    icon: 'assets/icons/meats/prosciutto.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Thịt thăn',
    value: 'thit-than',
    icon: 'assets/icons/meats/thit-than.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Thịt ba rọi',
    value: 'thit-ba-roi',
    icon: 'assets/icons/meats/thit-ba-roi.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Thịt bò',
    value: 'thit-bo',
    icon: 'assets/icons/meats/thit-bo.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Thịt cừu',
    value: 'thit-cuu',
    icon: 'assets/icons/meats/thit-cuu.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Thịt heo',
    value: 'thit-heo',
    icon: 'assets/icons/meats/thit-heo.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Tomahawk',
    value: 'tomahawk',
    icon: 'assets/icons/meats/tomahawk.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Trứng',
    value: 'trung',
    icon: 'assets/icons/meats/trung.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Trứng cút',
    value: 'trung-cut',
    icon: 'assets/icons/meats/trung-cut.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Ức gà',
    value: 'uc-ga',
    icon: 'assets/icons/meats/uc-ga.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Vịt',
    value: 'vit',
    icon: 'assets/icons/meats/vit.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Xúc xích',
    value: 'xuc-xich',
    icon: 'assets/icons/meats/xuc-xich.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Xúc xích cay',
    value: 'xuc-xich-cay',
    icon: 'assets/icons/meats/xuc-xich-cay.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Xúc xích hun khói',
    value: 'xuc-xich-hun-khoi',
    icon: 'assets/icons/meats/xuc-xich-hun-khoi.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Xúc xích Ý',
    value: 'xuc-xich-y',
    icon: 'assets/icons/meats/xuc-xich-y.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Xương chữ T',
    value: 'xuong-chu-T',
    icon: 'assets/icons/meats/xuong-chu-t.png',
    type: 'meats',
    defaultDuration: 1,
  ),
  Category(
    label: 'Xương sườn',
    value: 'xuong-suon',
    icon: 'assets/icons/meats/xuong-suon.png',
    type: 'meats',
    defaultDuration: 1,
  ),
];

List<Category> seafood = [
  Category(
    label: 'Ốc',
    value: 'oc',
    icon: 'assets/icons/seafood/oc.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Tôm sú',
    value: 'tom-su',
    icon: 'assets/icons/seafood/tom-su.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Tôm hùm',
    value: 'tom-hum',
    icon: 'assets/icons/seafood/tom-hum.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Trứng cá muối',
    value: 'trung-ca-muoi',
    icon: 'assets/icons/seafood/trung-ca-muoi.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Ngao',
    value: 'ngao',
    icon: 'assets/icons/seafood/ngao.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nhím biển',
    value: 'nhim-bien',
    icon: 'assets/icons/seafood/nhim-bien.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rong biển',
    value: 'rong-bien',
    icon: 'assets/icons/seafood/rong-bien.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Sò huyết',
    value: 'so-huyet',
    icon: 'assets/icons/seafood/so-huyet.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Trứng cá',
    value: 'trung-ca',
    icon: 'assets/icons/seafood/trung-ca.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Mực ống',
    value: 'muc-ong',
    icon: 'assets/icons/seafood/muc-ong.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Mực nang',
    value: 'muc-nang',
    icon: 'assets/icons/seafood/muc-nang.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hải sâm',
    value: 'hai-sam',
    icon: 'assets/icons/seafood/hai-sam.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cá tuyết',
    value: 'ca-tuyet',
    icon: 'assets/icons/seafood/ca-tuyet.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cá thu',
    value: 'ca-thu',
    icon: 'assets/icons/seafood/ca-thu.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cá hồi',
    value: 'ca-hoi',
    icon: 'assets/icons/seafood/ca-hoi.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cá khô',
    value: 'ca-kho',
    icon: 'assets/icons/seafood/ca-kho.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cá mèo',
    value: 'ca-meo',
    icon: 'assets/icons/seafood/ca-meo.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cá mòi',
    value: 'ca-moi',
    icon: 'assets/icons/seafood/ca-moi.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cá ngừ',
    value: 'ca-ngu',
    icon: 'assets/icons/seafood/ca-ngu.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cá hố',
    value: 'ca-ho',
    icon: 'assets/icons/seafood/ca-ho.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cá cơm',
    value: 'ca-com',
    icon: 'assets/icons/seafood/ca-com.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cá chình',
    value: 'ca-chinh',
    icon: 'assets/icons/seafood/ca-chinh.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cá',
    value: 'ca',
    icon: 'assets/icons/seafood/ca.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cua tuyết',
    value: 'cua-tuyet',
    icon: 'assets/icons/seafood/cua-tuyet.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Sứa',
    value: 'sua',
    icon: 'assets/icons/seafood/sua.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Trai',
    value: 'trai',
    icon: 'assets/icons/seafood/trai.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Tép',
    value: 'tep',
    icon: 'assets/icons/seafood/tep.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bạch tuộc',
    value: 'bach-tuoc',
    icon: 'assets/icons/seafood/bach-tuoc.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cua',
    value: 'cua',
    icon: 'assets/icons/seafood/cua.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hến',
    value: 'hen',
    icon: 'assets/icons/seafood/hen.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hàu',
    value: 'hau',
    icon: 'assets/icons/seafood/hau.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bào ngư',
    value: 'bao-ngu',
    icon: 'assets/icons/seafood/bao-ngu.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
  Category(
    label: 'Sò',
    value: 'so',
    icon: 'assets/icons/seafood/so.png',
    type: 'seafood',
    defaultDuration: 1,
  ),
];

List<Category> dishes = [
  Category(
    label: 'Món hầm',
    value: 'mon-ham',
    icon: 'assets/icons/dishes/mon-ham.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Garu',
    value: 'garu',
    icon: 'assets/icons/dishes/garu.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Mì ống',
    value: 'mi-ong',
    icon: 'assets/icons/dishes/mi-ong.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Onigiri',
    value: 'com-rong-bien',
    icon: 'assets/icons/dishes/com-rong-bien.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Chả cá Hàn Quốc',
    value: 'cha-ca-han-quoc',
    icon: 'assets/icons/dishes/cha-ca-han-quoc.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nước dùng',
    value: 'nuoc-dung',
    icon: 'assets/icons/dishes/nuoc-dung.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nori',
    value: 'nori',
    icon: 'assets/icons/dishes/nori.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Ngũ cốc',
    value: 'ngu-coc',
    icon: 'assets/icons/dishes/ngu-coc.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Pad Thái',
    value: 'pad-thai',
    icon: 'assets/icons/dishes/pad-thai.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cháo hải sản',
    value: 'chao-hai-san',
    icon: 'assets/icons/dishes/chao-hai-san.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Phở',
    value: 'pho',
    icon: 'assets/icons/dishes/pho.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Pizza',
    value: 'pizza',
    icon: 'assets/icons/dishes/pizza.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Pulkogi',
    value: 'pulkogi',
    icon: 'assets/icons/dishes/pulkogi.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Thịt nướng',
    value: 'thit-nuong',
    icon: 'assets/icons/dishes/thit-nuong.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Sashimi',
    value: 'sashimi',
    icon: 'assets/icons/dishes/sashimi.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rendang',
    value: 'rendang',
    icon: 'assets/icons/dishes/rendang.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh ngọt',
    value: 'banh-ngot',
    icon: 'assets/icons/dishes/banh-ngot.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Salad',
    value: 'salad',
    icon: 'assets/icons/dishes/salad.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Lạp xưởng',
    value: 'lap-xuong',
    icon: 'assets/icons/dishes/lap-xuong.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Mì gói',
    value: 'mi-goi',
    icon: 'assets/icons/dishes/mi-goi.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Mì nướng',
    value: 'mi-nuong',
    icon: 'assets/icons/dishes/mi-nuong.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Mì trộn',
    value: 'mi-tron',
    icon: 'assets/icons/dishes/mi-tron.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Mì udon',
    value: 'mi-udon',
    icon: 'assets/icons/dishes/mi-udon.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Kim chi',
    value: 'kim-chi',
    icon: 'assets/icons/dishes/kim-chi.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Kebab',
    value: 'kebab',
    icon: 'assets/icons/dishes/kebab.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hàng đông lạnh',
    value: 'hang-dong-lanh',
    icon: 'assets/icons/dishes/hang-dong-lanh.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Gỏi cuốn',
    value: 'goi-cuon',
    icon: 'assets/icons/dishes/goi-cuon.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Gimbap',
    value: 'gimbap',
    icon: 'assets/icons/dishes/gimbap.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Gnocchi',
    value: 'gnocchi',
    icon: 'assets/icons/dishes/gnocchi.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Gà rán',
    value: 'ga-ran',
    icon: 'assets/icons/dishes/ga-ran.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Dưa chuột muối',
    value: 'dua-chuot-muoi',
    icon: 'assets/icons/dishes/dua-chuot-muoi.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cơm trắng',
    value: 'com-trang',
    icon: 'assets/icons/dishes/com-trang.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cơm rang',
    value: 'com-rang',
    icon: 'assets/icons/dishes/com-rang.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cá hộp',
    value: 'ca-hop',
    icon: 'assets/icons/dishes/ca-hop.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cà ri',
    value: 'ca-ri',
    icon: 'assets/icons/dishes/ca-ri.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh mì kẹp xúc xích',
    value: 'banh-mi-kep-xuc-xich',
    icon: 'assets/icons/dishes/banh-mi-kep-xuc-xich.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh mì sandwich',
    value: 'banh-mi-sandwich',
    icon: 'assets/icons/dishes/banh-mi-sandwich.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh gối',
    value: 'banh-goi',
    icon: 'assets/icons/dishes/banh-goi.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hamburger',
    value: 'hamburger',
    icon: 'assets/icons/dishes/hamburger.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Canh',
    value: 'canh',
    icon: 'assets/icons/dishes/canh.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cháo',
    value: 'chao',
    icon: 'assets/icons/dishes/chao.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh mì',
    value: 'banh-mi',
    icon: 'assets/icons/dishes/banh-mi.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh bao',
    value: 'banh-bao',
    icon: 'assets/icons/dishes/banh-bao.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nem rán',
    value: 'nem-ran',
    icon: 'assets/icons/dishes/nem-ran.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cơm trộn',
    value: 'com-tron',
    icon: 'assets/icons/dishes/com-tron.png',
    type: 'dishes',
    defaultDuration: 1,
  ),
];

List<Category> dairyProducts = [
  Category(
    label: 'Roquefort',
    value: 'roquefort',
    icon: 'assets/icons/dairy_products/roquefort.png',
    type: 'dairy_products',
    defaultDuration: 1,
  ),
  Category(
    label: 'Sữa hạnh nhân',
    value: 'sua-hanh-nhan',
    icon: 'assets/icons/dairy_products/sua-hanh-nhan.png',
    type: 'dairy_products',
    defaultDuration: 1,
  ),
  Category(
    label: 'Sữa đậu nành',
    value: 'sua-dau-nanh',
    icon: 'assets/icons/dairy_products/sua-dau-nanh.png',
    type: 'dairy_products',
    defaultDuration: 1,
  ),
  Category(
    label: 'Thức uống lợi khuẩn',
    value: 'thuc-uong-loi-khuan',
    icon: 'assets/icons/dairy_products/thuc-uong-loi-khuan.png',
    type: 'dairy_products',
    defaultDuration: 1,
  ),
  Category(
    label: 'Trà sữa',
    value: 'tra-sua',
    icon: 'assets/icons/dairy_products/tra-sua.png',
    type: 'dairy_products',
    defaultDuration: 1,
  ),
  Category(
    label: 'Sữa dừa',
    value: 'sua-dua',
    icon: 'assets/icons/dairy_products/sua-dua.png',
    type: 'dairy_products',
    defaultDuration: 1,
  ),
  Category(
    label: 'Sữa chua',
    value: 'sua-chua',
    icon: 'assets/icons/dairy_products/sua-chua.png',
    type: 'dairy_products',
    defaultDuration: 1,
  ),
  Category(
    label: 'Sữa bột',
    value: 'sua-bot',
    icon: 'assets/icons/dairy_products/sua-bot.png',
    type: 'dairy_products',
    defaultDuration: 1,
  ),
  Category(
    label: 'Sữa tươi',
    value: 'sua-tuoi',
    icon: 'assets/icons/dairy_products/sua-tuoi.png',
    type: 'dairy_products',
    defaultDuration: 1,
  ),
  Category(
    label: 'Phô mát kem',
    value: 'pho-mat-kem',
    icon: 'assets/icons/dairy_products/pho-mat-kem.png',
    type: 'dairy_products',
    defaultDuration: 1,
  ),
  Category(
    label: 'Phô mai',
    value: 'pho-mai',
    icon: 'assets/icons/dairy_products/pho-mai.png',
    type: 'dairy_products',
    defaultDuration: 1,
  ),
  Category(
    label: 'Phô mai mozzarella',
    value: 'pho-mai-mozzarella',
    icon: 'assets/icons/dairy_products/pho-mai-mozzarella.png',
    type: 'dairy_products',
    defaultDuration: 1,
  ),
  Category(
    label: 'Ricotta',
    value: 'ricotta',
    icon: 'assets/icons/dairy_products/ricotta.png',
    type: 'dairy_products',
    defaultDuration: 1,
  ),
  Category(
    label: 'Kem tươi',
    value: 'kem-tuoi',
    icon: 'assets/icons/dairy_products/kem-tuoi.png',
    type: 'dairy_products',
    defaultDuration: 1,
  ),
  Category(
    label: 'Kem chua',
    value: 'kem-chua',
    icon: 'assets/icons/dairy_products/kem-chua.png',
    type: 'dairy_products',
    defaultDuration: 1,
  ),
  Category(
    label: 'Gouda',
    value: 'gouda',
    icon: 'assets/icons/dairy_products/gouda.png',
    type: 'dairy_products',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cheddar',
    value: 'cheddar',
    icon: 'assets/icons/dairy_products/cheddar.png',
    type: 'dairy_products',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bơ',
    value: 'bo',
    icon: 'assets/icons/dairy_products/bo.png',
    type: 'dairy_products',
    defaultDuration: 1,
  ),
];

List<Category> drinks = [
  Category(
    label: 'Cà phê',
    value: 'ca-phe',
    icon: 'assets/icons/drinks/ca-phe.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Coca',
    value: 'coca',
    icon: 'assets/icons/drinks/coca.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hạt cà phê',
    value: 'hat-ca-phe',
    icon: 'assets/icons/drinks/hat-ca-phe.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nước cam',
    value: 'nuoc-cam',
    icon: 'assets/icons/drinks/nuoc-cam.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nước chanh',
    value: 'nuoc-chanh',
    icon: 'assets/icons/drinks/nuoc-chanh.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nước dừa',
    value: 'nuoc-dua',
    icon: 'assets/icons/drinks/nuoc-dua.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nước ép trái cây',
    value: 'nuoc-ep-trai-cay',
    icon: 'assets/icons/drinks/nuoc-ep-trai-cay.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nước mía',
    value: 'nuoc-mia',
    icon: 'assets/icons/drinks/nuoc-mia.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nước ngọt có ga',
    value: 'nuoc-ngot-co-ga',
    icon: 'assets/icons/drinks/nuoc-ngot-co-ga.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nước suối',
    value: 'nuoc-suoi',
    icon: 'assets/icons/drinks/nuoc-suoi.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nước suối có ga',
    value: 'nuoc-suoi-co-ga',
    icon: 'assets/icons/drinks/nuoc-suoi-co-ga.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nước tăng lực',
    value: 'nuoc-tang-luc',
    icon: 'assets/icons/drinks/nuoc-tang-luc.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nước táo',
    value: 'nuoc-tao',
    icon: 'assets/icons/drinks/nuoc-tao.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nước tonic',
    value: 'nuoc-tonic',
    icon: 'assets/icons/drinks/nuoc-tonic.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nước uống thể thao',
    value: 'nuoc-uong-the-thao',
    icon: 'assets/icons/drinks/nuoc-uong-the-thao.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Sô cô la nóng',
    value: 'so-co-la-nong',
    icon: 'assets/icons/drinks/so-co-la-nong.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Soda lon',
    value: 'soda-lon',
    icon: 'assets/icons/drinks/soda-lon.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Trà',
    value: 'tra',
    icon: 'assets/icons/drinks/tra.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Trà bạc hà',
    value: 'tra-bac-ha',
    icon: 'assets/icons/drinks/tra-bac-ha.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Trà chanh',
    value: 'tra-chanh',
    icon: 'assets/icons/drinks/tra-chanh.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Trà dâm bụt',
    value: 'tra-dam-but',
    icon: 'assets/icons/drinks/tra-dam-but.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Trà gừng',
    value: 'tra-gung',
    icon: 'assets/icons/drinks/tra-gung.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Trà hoa cúc',
    value: 'tra-hoa-cuc',
    icon: 'assets/icons/drinks/tra-hoa-cuc.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Trà hoa nhài',
    value: 'tra-hoa-nhai',
    icon: 'assets/icons/drinks/tra-hoa-nhai.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Trà ô long',
    value: 'tra-o-long',
    icon: 'assets/icons/drinks/tra-o-long.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Trà túi lọc',
    value: 'tra-tui-loc',
    icon: 'assets/icons/drinks/tra-tui-loc.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
  Category(
    label: 'Trà xanh',
    value: 'tra-xanh',
    icon: 'assets/icons/drinks/tra-xanh.png',
    type: 'drinks',
    defaultDuration: 1,
  ),
];

List<Category> alcohol = [
  Category(
    label: 'Bia',
    value: 'bia',
    icon: 'assets/icons/alcohol/bia.png',
    type: 'alcohol',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bia không cồn',
    value: 'bia-khong-con',
    icon: 'assets/icons/alcohol/bia-khong-con.png',
    type: 'alcohol',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cocktail',
    value: 'cocktail',
    icon: 'assets/icons/alcohol/cocktail.png',
    type: 'alcohol',
    defaultDuration: 1,
  ),
  Category(
    label: 'Punch',
    value: 'punch',
    icon: 'assets/icons/alcohol/punch.png',
    type: 'alcohol',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rượu absinthe',
    value: 'ruou-absinthe',
    icon: 'assets/icons/alcohol/ruou-absinthe.png',
    type: 'alcohol',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rượu brandy',
    value: 'ruou-brandy',
    icon: 'assets/icons/alcohol/ruou-brandy.png',
    type: 'alcohol',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rượu cà phê',
    value: 'ruou-ca-phe',
    icon: 'assets/icons/alcohol/ruou-ca-phe.png',
    type: 'alcohol',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rươu gin',
    value: 'ruou-gin',
    icon: 'assets/icons/alcohol/ruou-gin.png',
    type: 'alcohol',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rượu makgeolli',
    value: 'ruou-makgeolli',
    icon: 'assets/icons/alcohol/ruou-makgeolli.png',
    type: 'alcohol',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rượu mezcal',
    value: 'ruou-mezcal',
    icon: 'assets/icons/alcohol/ruou-mezcal.png',
    type: 'alcohol',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rượu mùi thảo dược',
    value: 'ruou-mui-thao-duoc',
    icon: 'assets/icons/alcohol/ruou-mui-thao-duoc.png',
    type: 'alcohol',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rượu rum',
    value: 'ruou-rum',
    icon: 'assets/icons/alcohol/ruou-rum.png',
    type: 'alcohol',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rượu sake',
    value: 'ruou-sake',
    icon: 'assets/icons/alcohol/ruou-sake.png',
    type: 'alcohol',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rượu sâm banh',
    value: 'ruou-sam-banh',
    icon: 'assets/icons/alcohol/ruou-sam-banh.png',
    type: 'alcohol',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rượu soju',
    value: 'ruou-soju',
    icon: 'assets/icons/alcohol/ruou-soju.png',
    type: 'alcohol',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rượu tequila',
    value: 'ruou-tequila',
    icon: 'assets/icons/alcohol/ruou-tequila.png',
    type: 'alcohol',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rượu vang',
    value: 'ruou-vang',
    icon: 'assets/icons/alcohol/ruou-vang.png',
    type: 'alcohol',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rượu vermouth',
    value: 'ruou-vermouth',
    icon: 'assets/icons/alcohol/ruou-vermouth.png',
    type: 'alcohol',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rượu vodka',
    value: 'ruou-vodka',
    icon: 'assets/icons/alcohol/ruou-vodka.png',
    type: 'alcohol',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rượu whisky',
    value: 'ruou-whisky',
    icon: 'assets/icons/alcohol/ruou-whisky.png',
    type: 'alcohol',
    defaultDuration: 1,
  ),
  Category(
    label: 'Sangria',
    value: 'sangria',
    icon: 'assets/icons/alcohol/sangria.png',
    type: 'alcohol',
    defaultDuration: 1,
  ),
];

List<Category> sauces = [
  Category(
    label: 'Điệu salsa',
    value: 'dieu-salsa',
    icon: 'assets/icons/sauces/dieu-salsa.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Đường',
    value: 'duong',
    icon: 'assets/icons/sauces/duong.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Gói nước sốt',
    value: 'goi-nuoc-sot',
    icon: 'assets/icons/sauces/goi-nuoc-sot.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Mật ong',
    value: 'mat-ong',
    icon: 'assets/icons/sauces/mat-ong.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Muối',
    value: 'muoi',
    icon: 'assets/icons/sauces/muoi.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Mứt',
    value: 'mut',
    icon: 'assets/icons/sauces/mut.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Mù tạt vàng',
    value: 'mu-tat-vang',
    icon: 'assets/icons/sauces/mu-tat-vang.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Mù tạt xanh',
    value: 'mu-tat-xanh',
    icon: 'assets/icons/sauces/mu-tat-xanh.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Mứt sô cô la',
    value: 'mut-so-co-la',
    icon: 'assets/icons/sauces/mut-so-co-la.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nước chanh',
    value: 'nuoc-chanh',
    icon: 'assets/icons/sauces/nuoc-chanh.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nước sốt BBQ',
    value: 'nuoc-sot-bbq',
    icon: 'assets/icons/sauces/nuoc-sot-bbq.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nước sốt cay',
    value: 'nuoc-sot-cay',
    icon: 'assets/icons/sauces/nuoc-sot-cay.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nước sốt pesto',
    value: 'nuoc-sot-pesto',
    icon: 'assets/icons/sauces/nuoc-sot-pesto.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nước tương',
    value: 'nuoc-tuong',
    icon: 'assets/icons/sauces/nuoc-tuong.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nước xốt mè rang',
    value: 'nuoc-xot-me-rang',
    icon: 'assets/icons/sauces/nuoc-xot-me-rang.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Siro',
    value: 'siro',
    icon: 'assets/icons/sauces/siro.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Siro agave',
    value: 'siro-agave',
    icon: 'assets/icons/sauces/siro-agave.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Siro bắp',
    value: 'siro-bap',
    icon: 'assets/icons/sauces/siro-bap.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Siro phong',
    value: 'siro-phong',
    icon: 'assets/icons/sauces/siro-phong.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Sốt bít tết',
    value: 'sot-bit-tet',
    icon: 'assets/icons/sauces/sot-bit-tet.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Sốt hàu',
    value: 'sot-hau',
    icon: 'assets/icons/sauces/sot-hau.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Sốt mayonaise',
    value: 'sot-mayonaise',
    icon: 'assets/icons/sauces/sot-mayonaise.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Sốt táo',
    value: 'sot-tao',
    icon: 'assets/icons/sauces/sot-tao.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Tương cà',
    value: 'tuong-ca',
    icon: 'assets/icons/sauces/tuong-ca.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
  Category(
    label: 'Tương ớt',
    value: 'tuong-ot',
    icon: 'assets/icons/sauces/tuong-ot.png',
    type: 'sauces',
    defaultDuration: 1,
  ),
];

List<Category> spices = [
  Category(
    label: 'Bột ớt',
    value: 'bot-ot',
    icon: 'assets/icons/spices/bot-ot.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bột cà ri',
    value: 'bot-ca-ri',
    icon: 'assets/icons/spices/bot-ca-ri.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cây bạc hà',
    value: 'cay-bac-ha',
    icon: 'assets/icons/spices/cay-bac-ha.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cây bách hoa',
    value: 'cay-bach-hoa',
    icon: 'assets/icons/spices/cay-bach-hoa.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cây hồi',
    value: 'cay-hoi',
    icon: 'assets/icons/spices/cay-hoi.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cây mê điệt',
    value: 'cay-me-diet',
    icon: 'assets/icons/spices/cay-me-diet.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Đinh hương',
    value: 'dinh-huong',
    icon: 'assets/icons/spices/dinh-huong.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Gừng',
    value: 'gung',
    icon: 'assets/icons/spices/gung.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hành khô',
    value: 'hanh-kho',
    icon: 'assets/icons/spices/hanh-kho.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hồ tiêu',
    value: 'ho-tieu',
    icon: 'assets/icons/spices/ho-tieu.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Húng quế',
    value: 'hung-que',
    icon: 'assets/icons/spices/hung-que.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Lá nguyệt quế',
    value: 'la-nguyet-que',
    icon: 'assets/icons/spices/la-nguyet-que.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Mùi tây',
    value: 'mui-tay',
    icon: 'assets/icons/spices/mui-tay.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nghệ',
    value: 'nghe',
    icon: 'assets/icons/spices/nghe.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nghệ tây',
    value: 'nghe-tay',
    icon: 'assets/icons/spices/nghe-tay.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Nhục đậu khấu',
    value: 'nhuc-dau-khau',
    icon: 'assets/icons/spices/nhuc-dau-khau.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Quả me',
    value: 'qua-me',
    icon: 'assets/icons/spices/qua-me.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Quế',
    value: 'que',
    icon: 'assets/icons/spices/que.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rau kinh giới',
    value: 'rau-kinh-gioi',
    icon: 'assets/icons/spices/rau-kinh-gioi.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rau mùi',
    value: 'rau-mui',
    icon: 'assets/icons/spices/rau-mui.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rau răm',
    value: 'rau-ram',
    icon: 'assets/icons/spices/rau-ram.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rau thì là',
    value: 'rau-thi-la',
    icon: 'assets/icons/spices/rau-thi-la.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Rau thơm',
    value: 'rau-thom',
    icon: 'assets/icons/spices/rau-thom.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Thì là',
    value: 'thi-la',
    icon: 'assets/icons/spices/thi-la.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Tỏi',
    value: 'toi',
    icon: 'assets/icons/spices/toi.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Truffle',
    value: 'truffle',
    icon: 'assets/icons/spices/truffle.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Vanilla',
    value: 'vanilla',
    icon: 'assets/icons/spices/vanilla.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Xạ hương',
    value: 'xa-huong',
    icon: 'assets/icons/spices/xa-huong.png',
    type: 'spices',
    defaultDuration: 1,
  ),
  Category(
    label: 'Xô thơm',
    value: 'xo-thom',
    icon: 'assets/icons/spices/xo-thom.png',
    type: 'spices',
    defaultDuration: 1,
  ),
];

List<Category> bread = [
  Category(
    label: 'Bánh con sò',
    value: 'banh-con-so',
    icon: 'assets/icons/bread/banh-con-so.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh crepe',
    value: 'banh-crepe',
    icon: 'assets/icons/bread/banh-crepe.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh focaccia',
    value: 'banh-focaccia',
    icon: 'assets/icons/bread/banh-focaccia.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh kếp',
    value: 'banh-kep',
    icon: 'assets/icons/bread/banh-kep.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh mì gối',
    value: 'banh-mi-goi',
    icon: 'assets/icons/bread/banh-mi-goi.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh mì hoa cúc',
    value: 'banh-mi-hoa-cuc',
    icon: 'assets/icons/bread/banh-mi-hoa-cuc.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh mì ổ',
    value: 'banh-mi-o',
    icon: 'assets/icons/bread/banh-mi-o.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh mì Pháp',
    value: 'banh-mi-phap',
    icon: 'assets/icons/bread/banh-mi-phap.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh mì roti',
    value: 'banh-mi-roti',
    icon: 'assets/icons/bread/banh-mi-roti.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh mì vòng',
    value: 'banh-mi-vong',
    icon: 'assets/icons/bread/banh-mi-vong.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh nướng',
    value: 'banh-nuong',
    icon: 'assets/icons/bread/banh-nuong.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh nướng xốp',
    value: 'banh-nuong-xop',
    icon: 'assets/icons/bread/banh-nuong-xop.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh quế',
    value: 'banh-que',
    icon: 'assets/icons/bread/banh-que.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh quy que',
    value: 'banh-quy-que',
    icon: 'assets/icons/bread/banh-quy-que.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh quy xoắn',
    value: 'banh-quy-xoan',
    icon: 'assets/icons/bread/banh-quy-xoan.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh scone',
    value: 'banh-scone',
    icon: 'assets/icons/bread/banh-scone.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh sữa nhỏ',
    value: 'banh-sua-nho',
    icon: 'assets/icons/bread/banh-sua-nho.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh sừng bò',
    value: 'banh-sung-bo',
    icon: 'assets/icons/bread/banh-sung-bo.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh vòng',
    value: 'banh-vong',
    icon: 'assets/icons/bread/banh-vong.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bột chua',
    value: 'bot-chua',
    icon: 'assets/icons/bread/bot-chua.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Ciabatta',
    value: 'ciabatta',
    icon: 'assets/icons/bread/ciabatta.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Dorayaki',
    value: 'dorayaki',
    icon: 'assets/icons/bread/dorayaki.png',
    type: 'bread',
    defaultDuration: 1,
  ),
  Category(
    label: 'Quế cuộn',
    value: 'que-cuon',
    icon: 'assets/icons/bread/que-cuon.png',
    type: 'bread',
    defaultDuration: 1,
  ),
];

List<Category> desserts = [
  Category(
    label: 'Baklava',
    value: 'baklava',
    icon: 'assets/icons/desserts/baklava.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh Brownie',
    value: 'banh-brownie',
    icon: 'assets/icons/desserts/banh-brownie.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh cuộn',
    value: 'banh-cuon',
    icon: 'assets/icons/desserts/banh-cuon.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh cupcake',
    value: 'banh-cupcake',
    icon: 'assets/icons/desserts/banh-cupcake.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh eclair',
    value: 'banh-eclair',
    icon: 'assets/icons/desserts/banh-eclair.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh gừng',
    value: 'banh-gung',
    icon: 'assets/icons/desserts/banh-gung.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh macaron',
    value: 'banh-macaron',
    icon: 'assets/icons/desserts/banh-macaron.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh nachos',
    value: 'banh-nachos',
    icon: 'assets/icons/desserts/banh-nachos.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh ngọt',
    value: 'banh-ngot',
    icon: 'assets/icons/desserts/banh-ngot.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh ống khói',
    value: 'banh-ong-khoi',
    icon: 'assets/icons/desserts/banh-ong-khoi.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh pudding',
    value: 'banh-pudding',
    icon: 'assets/icons/desserts/banh-pudding.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh quy',
    value: 'banh-quy',
    icon: 'assets/icons/desserts/banh-quy.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh quy may mắn',
    value: 'banh-quy-may-man',
    icon: 'assets/icons/desserts/banh-quy-may-man.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh quy nho',
    value: 'banh-quy-nho',
    icon: 'assets/icons/desserts/banh-quy-nho.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh quy quế sô cô la',
    value: 'banh-quy-que-so-co-la',
    icon: 'assets/icons/desserts/banh-quy-que-so-co-la.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh trứng',
    value: 'banh-trung',
    icon: 'assets/icons/desserts/banh-trung.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bánh trung thu',
    value: 'banh-trung-thu',
    icon: 'assets/icons/desserts/banh-trung-thu.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bắp rang bơ',
    value: 'bap-rang-bo',
    icon: 'assets/icons/desserts/bap-rang-bo.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bim bim',
    value: 'bim-bim',
    icon: 'assets/icons/desserts/bim-bim.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Brioche',
    value: 'brioche',
    icon: 'assets/icons/desserts/brioche.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Canape',
    value: 'canape',
    icon: 'assets/icons/desserts/canape.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Caramen',
    value: 'caramen',
    icon: 'assets/icons/desserts/caramen.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Cracker',
    value: 'cracker',
    icon: 'assets/icons/desserts/cracker.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Đá bào',
    value: 'da-bao',
    icon: 'assets/icons/desserts/da-bao.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Dango',
    value: 'dango',
    icon: 'assets/icons/desserts/dango.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Gấu gummy',
    value: 'gau-gummy',
    icon: 'assets/icons/desserts/gau-gummy.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Kem',
    value: 'kem',
    icon: 'assets/icons/desserts/kem.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Kẹo',
    value: 'keo',
    icon: 'assets/icons/desserts/keo.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Kẹo cao su',
    value: 'keo-cao-su',
    icon: 'assets/icons/desserts/keo-cao-su.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Kẹo chíp chíp',
    value: 'keo-chip-chip',
    icon: 'assets/icons/desserts/keo-chip-chip.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Kẹo dẻo',
    value: 'keo-deo',
    icon: 'assets/icons/desserts/keo-deo.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Kẹo mút',
    value: 'keo-mut',
    icon: 'assets/icons/desserts/keo-mut.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Khoai tây chiên',
    value: 'khoai-tay-chien',
    icon: 'assets/icons/desserts/khoai-tay-chien.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Khoai tây chiên dài',
    value: 'khoai-tay-chien-dai',
    icon: 'assets/icons/desserts/khoai-tay-chien-dai.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Pavlova',
    value: 'pavlova',
    icon: 'assets/icons/desserts/pavlova.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Poutine',
    value: 'poutine',
    icon: 'assets/icons/desserts/poutine.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Sô cô la',
    value: 'so-co-la',
    icon: 'assets/icons/desserts/so-co-la.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Thanh năng lượng',
    value: 'thanh-nang-luong',
    icon: 'assets/icons/desserts/thanh-nang-luong.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Tiramisu',
    value: 'tiramisu',
    icon: 'assets/icons/desserts/tiramisu.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Tổ ong',
    value: 'to-ong',
    icon: 'assets/icons/desserts/to-ong.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Tteok',
    value: 'tteok',
    icon: 'assets/icons/desserts/tteok.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Yakgwa',
    value: 'yakgwa',
    icon: 'assets/icons/desserts/yakgwa.png',
    type: 'desserts',
    defaultDuration: 1,
  ),
];

List<Category> nuts = [
  Category(
    label: 'Cacao',
    value: 'cacao',
    icon: 'assets/icons/nuts/cacao.png',
    type: 'nuts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Đậu phộng',
    value: 'dau-phong',
    icon: 'assets/icons/nuts/dau-phong.png',
    type: 'nuts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hạnh nhân',
    value: 'hanh-nhan',
    icon: 'assets/icons/nuts/hanh-nhan.png',
    type: 'nuts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hạt bí',
    value: 'hat-bi',
    icon: 'assets/icons/nuts/hat-bi.png',
    type: 'nuts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hạt brazil',
    value: 'hat-brazil',
    icon: 'assets/icons/nuts/hat-brazil.png',
    type: 'nuts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hạt dẻ',
    value: 'hat-de',
    icon: 'assets/icons/nuts/hat-de.png',
    type: 'nuts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hạt dẻ cười',
    value: 'hat-de-cuoi',
    icon: 'assets/icons/nuts/hat-de-cuoi.png',
    type: 'nuts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hạt điều',
    value: 'hat-dieu',
    icon: 'assets/icons/nuts/hat-dieu.png',
    type: 'nuts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hạt hướng dương',
    value: 'hat-huong-duong',
    icon: 'assets/icons/nuts/hat-huong-duong.png',
    type: 'nuts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hạt phỉ',
    value: 'hat-phi',
    icon: 'assets/icons/nuts/hat-phi.png',
    type: 'nuts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hạt sồi',
    value: 'hat-soi',
    icon: 'assets/icons/nuts/hat-soi.png',
    type: 'nuts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hạt thông',
    value: 'hat-thong',
    icon: 'assets/icons/nuts/hat-thong.png',
    type: 'nuts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hồ đào',
    value: 'ho-dao',
    icon: 'assets/icons/nuts/ho-dao.png',
    type: 'nuts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Macadamia',
    value: 'macadamia',
    icon: 'assets/icons/nuts/macadamia.png',
    type: 'nuts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Mè',
    value: 'me',
    icon: 'assets/icons/nuts/me.png',
    type: 'nuts',
    defaultDuration: 1,
  ),
  Category(
    label: 'Quả óc chó',
    value: 'qua-oc-cho',
    icon: 'assets/icons/nuts/qua-oc-cho.png',
    type: 'nuts',
    defaultDuration: 1,
  ),
];

List<Category> cereals = [
  Category(
    label: 'Bột mì',
    value: 'bot-mi',
    icon: 'assets/icons/cereals/bot-mi.png',
    type: 'cereals',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bột ngô',
    value: 'bot-ngo',
    icon: 'assets/icons/cereals/bot-ngo.png',
    type: 'cereals',
    defaultDuration: 1,
  ),
  Category(
    label: 'Bột yến mạch',
    value: 'bot-yen-mach',
    icon: 'assets/icons/cereals/bot-yen-mach.png',
    type: 'cereals',
    defaultDuration: 1,
  ),
  Category(
    label: 'Đậu cove',
    value: 'dau-cove',
    icon: 'assets/icons/cereals/dau-cove.png',
    type: 'cereals',
    defaultDuration: 1,
  ),
  Category(
    label: 'Đậu đen',
    value: 'dau-den',
    icon: 'assets/icons/cereals/dau-den.png',
    type: 'cereals',
    defaultDuration: 1,
  ),
  Category(
    label: 'Đậu đỏ',
    value: 'dau-do',
    icon: 'assets/icons/cereals/dau-do.png',
    type: 'cereals',
    defaultDuration: 1,
  ),
  Category(
    label: 'Đậu lăng',
    value: 'dau-lang',
    icon: 'assets/icons/cereals/dau-lang.png',
    type: 'cereals',
    defaultDuration: 1,
  ),
  Category(
    label: 'Đậu nành luộc',
    value: 'dau-nanh-luoc',
    icon: 'assets/icons/cereals/dau-nanh-luoc.png',
    type: 'cereals',
    defaultDuration: 1,
  ),
  Category(
    label: 'Đậu thận',
    value: 'dau-than',
    icon: 'assets/icons/cereals/dau-than.png',
    type: 'cereals',
    defaultDuration: 1,
  ),
  Category(
    label: 'Đậu tương',
    value: 'dau-tuong',
    icon: 'assets/icons/cereals/dau-tuong.png',
    type: 'cereals',
    defaultDuration: 1,
  ),
  Category(
    label: 'Đậu xanh',
    value: 'dau-xanh',
    icon: 'assets/icons/cereals/dau-xanh.png',
    type: 'cereals',
    defaultDuration: 1,
  ),
  Category(
    label: 'Đậu nành',
    value: 'dau-nanh',
    icon: 'assets/icons/cereals/dau-nanh.png',
    type: 'cereals',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hạt chia',
    value: 'hat-chia',
    icon: 'assets/icons/cereals/hat-chia.png',
    type: 'cereals',
    defaultDuration: 1,
  ),
  Category(
    label: 'Hạt diêm mạch',
    value: 'hat-diem-mach',
    icon: 'assets/icons/cereals/hat-diem-mach.png',
    type: 'cereals',
    defaultDuration: 1,
  ),
  Category(
    label: 'Kiều mạch',
    value: 'kieu-mach',
    icon: 'assets/icons/cereals/kieu-mach.png',
    type: 'cereals',
    defaultDuration: 1,
  ),
  Category(
    label: 'Lúa gạo',
    value: 'lua-gao',
    icon: 'assets/icons/cereals/lua-gao.png',
    type: 'cereals',
    defaultDuration: 1,
  ),
  Category(
    label: 'Lúa mạch',
    value: 'lua-mach',
    icon: 'assets/icons/cereals/lua-mach.png',
    type: 'cereals',
    defaultDuration: 1,
  ),
  Category(
    label: 'Lúa mạch đen',
    value: 'lua-mach-den',
    icon: 'assets/icons/cereals/lua-mach-den.png',
    type: 'cereals',
    defaultDuration: 1,
  ),
  Category(
    label: 'Men',
    value: 'men',
    icon: 'assets/icons/cereals/men.png',
    type: 'cereals',
    defaultDuration: 1,
  ),
];

List<Category> etc = [
  Category(
    label: 'Chất đạm',
    value: 'chat-dam',
    icon: 'assets/icons/etc/chat-dam.png',
    type: 'etc',
    defaultDuration: 1,
  ),
  Category(
    label: 'Dầu cá',
    value: 'dau-ca',
    icon: 'assets/icons/etc/dau-ca.png',
    type: 'etc',
    defaultDuration: 1,
  ),
  Category(
    label: 'Halal',
    value: 'halal',
    icon: 'assets/icons/etc/halal.png',
    type: 'etc',
    defaultDuration: 1,
  ),
  Category(
    label: 'Iftar',
    value: 'iftar',
    icon: 'assets/icons/etc/iftar.png',
    type: 'etc',
    defaultDuration: 1,
  ),
  Category(
    label: 'Kẹo Halloween',
    value: 'keo-halloween',
    icon: 'assets/icons/etc/keo-halloween.png',
    type: 'etc',
    defaultDuration: 1,
  ),
  Category(
    label: 'Mặt nạ',
    value: 'mat-na',
    icon: 'assets/icons/etc/mat-na.png',
    type: 'etc',
    defaultDuration: 1,
  ),
  Category(
    label: 'Mỹ phẩm',
    value: 'my-pham',
    icon: 'assets/icons/etc/my-pham.png',
    type: 'etc',
    defaultDuration: 1,
  ),
  Category(
    label: 'Probiotic',
    value: 'probiotic',
    icon: 'assets/icons/etc/probiotic.png',
    type: 'etc',
    defaultDuration: 1,
  ),
  Category(
    label: 'Sữa bột trẻ em',
    value: 'sua-bot-tre-em',
    icon: 'assets/icons/etc/sua-bot-tre-em.png',
    type: 'etc',
    defaultDuration: 1,
  ),
  Category(
    label: 'Thức ăn trẻ em',
    value: 'thuc-an-tre-em',
    icon: 'assets/icons/etc/thuc-an-tre-em.png',
    type: 'etc',
    defaultDuration: 1,
  ),
  Category(
    label: 'Thức ăn vật nuôi',
    value: 'thuc-an-vat-nuoi',
    icon: 'assets/icons/etc/thuc-an-vat-nuoi.png',
    type: 'etc',
    defaultDuration: 1,
  ),
  Category(
    label: 'Thuốc',
    value: 'thuoc',
    icon: 'assets/icons/etc/thuoc.png',
    type: 'etc',
    defaultDuration: 1,
  ),
  Category(
    label: 'Trứng phục sinh',
    value: 'trung-phuc-sinh',
    icon: 'assets/icons/etc/trung-phuc-sinh.png',
    type: 'etc',
    defaultDuration: 1,
  ),
  Category(
    label: 'Vitamin',
    value: 'vitamin',
    icon: 'assets/icons/etc/vitamin.png',
    type: 'etc',
    defaultDuration: 1,
  ),
];

List<Food> foods = [
  Food(
    categories: fruits,
    value: 'fruits',
    label: 'Trái cây',
    icon: 'assets/icons/fruits/fruits.png',
  ),
  Food(
    categories: meats,
    value: 'meats',
    label: 'Thịt',
    icon: 'assets/icons/meats/meats.png',
  ),
  Food(
    categories: vegetables,
    value: 'vegetables',
    label: 'Rau',
    icon: 'assets/icons/vegetables/vegetables.png',
  ),
  Food(
    categories: dairyProducts,
    value: 'dairy_products',
    label: 'Sản phẩm từ sữa',
    icon: 'assets/icons/dairy_products/dairy_products.png',
  ),
  Food(
    categories: dishes,
    value: 'dishes',
    label: 'Món ăn',
    icon: 'assets/icons/dishes/dishes.png',
  ),
  Food(
    categories: seafood,
    value: 'seafood',
    label: 'Hải sản',
    icon: 'assets/icons/seafood/seafood.png',
  ),
  Food(
    categories: drinks,
    value: 'drinks',
    label: 'Đồ uống',
    icon: 'assets/icons/drinks/drinks.png',
  ),
  Food(
    categories: alcohol,
    value: 'alcohol',
    label: 'Rượu',
    icon: 'assets/icons/alcohol/alcohol.png',
  ),
  Food(
    categories: sauces,
    value: 'sauces',
    label: 'Nước xốt',
    icon: 'assets/icons/sauces/sauces.png',
  ),
  Food(
    categories: spices,
    value: 'spices',
    label: 'Gia vị',
    icon: 'assets/icons/spices/spices.png',
  ),
  Food(
    categories: bread,
    value: 'bread',
    label: 'Bánh mì',
    icon: 'assets/icons/bread/bread.png',
  ),
  Food(
    categories: desserts,
    value: 'desserts',
    label: 'Tráng miệng',
    icon: 'assets/icons/desserts/desserts.png',
  ),
  Food(
    categories: nuts,
    value: 'nuts',
    label: 'Quả hạch',
    icon: 'assets/icons/nuts/nuts.png',
  ),
  Food(
    categories: cereals,
    value: 'cereals',
    label: 'Ngũ cốc',
    icon: 'assets/icons/cereals/cereals.png',
  ),
  Food(
    categories: etc,
    value: 'etc',
    label: 'Vân vân.',
    icon: 'assets/icons/etc/etc.png',
  ),
];

List<Category> allCategories = [
  ...fruits,
  ...meats,
  ...vegetables,
  ...dairyProducts,
  ...dishes,
  ...seafood,
  ...drinks,
  ...alcohol,
  ...sauces,
  ...spices,
  ...bread,
  ...desserts,
  ...nuts,
  ...cereals,
  ...etc
];
List<Item> reactions = [
  Item(
      value: 'delicious',
      label: 'Delicious',
      icon: 'assets/icons/i16/eat.png',
    ),
    Item(
      value: 'love',
      label: 'Yêu thích',
      icon: 'assets/icons/i16/heart.png',
    ),
    Item(
      value: 'like',
      label: 'Thích',
      icon: 'assets/icons/i16/vo-tay.png',
    ),
];
