import 'package:frontend/types/food.dart';

List<Category> fruits = [
  Category('tao', 1, 'Táo', 'assets/icons/fruits/tao.png', 'fruits'),
  Category('cam', 1, 'Cam', 'assets/icons/fruits/cam.png', 'fruits'),
  Category(
      'dau-tay', 1, 'Dâu tây', 'assets/icons/fruits/dau-tay.png', 'fruits'),
  // Category('chuoi', 1, 'Chuối', 'assets/icons/fruits/chuoi.png', 'fruits'),
  // Category('du-du', 1, 'Đu đủ', 'assets/icons/fruits/du-du.png', 'fruits'),
  // Category('dao', 1, 'Đào', 'assets/icons/fruits/dao.png', 'fruits'),
  // Category('o-liu', 1, 'Ô liu', 'assets/icons/fruits/o-liu.png', 'fruits'),
  // Category('vai', 1, 'Vải', 'assets/icons/fruits/vai.png', 'fruits'),
  // Category('viet-quat', 1, 'Việt quất', 'assets/icons/fruits/viet-quat.png',
  //     'fruits'),
  // Category(
  //     'tao-xanh', 1, 'Táo xanh', 'assets/icons/fruits/tao-xanh.png', 'fruits'),
  // Category(
  //     'tao-tau', 1, 'Táo tàu', 'assets/icons/fruits/tao-tau.png', 'fruits'),
  // Category('khe', 1, 'Khế', 'assets/icons/fruits/khe.png', 'fruits'),
  // Category('sau-rieng', 1, 'Sầu riêng', 'assets/icons/fruits/sau-rieng.png',
  //     'fruits'),
  // Category('luu', 1, 'Lựu', 'assets/icons/fruits/luu.png', 'fruits'),
  // Category('xoai', 1, 'Xoài', 'assets/icons/fruits/xoai.png', 'fruits'),
  // Category('oi', 1, 'Ổi', 'assets/icons/fruits/oi.png', 'fruits'),
  // Category('chom-chom', 1, 'Chôm chôm', 'assets/icons/fruits/chom-chom.png',
  //     'fruits'),
  // Category('bo', 1, 'Bơ', 'assets/icons/fruits/bo.png', 'fruits'),
  // Category('thanh-long', 1, 'Thanh long', 'assets/icons/fruits/thanh-long.png',
  //     'fruits'),
  // Category('sung', 1, 'Sung', 'assets/icons/fruits/sung.png', 'fruits'),
  // Category(
  //     'nho-tim', 1, 'Nho tím', 'assets/icons/fruits/nho-tim.png', 'fruits'),
  // Category('mong', 1, 'Mọng', 'assets/icons/fruits/mong.png', 'fruits'),
  // Category('mo', 1, 'Mơ', 'assets/icons/fruits/mo.png', 'fruits'),
  // Category(
  //     'mang-cut', 1, 'Măng cụt', 'assets/icons/fruits/mang-cut.png', 'fruits'),
  // Category('kiwi', 1, 'Kiwi', 'assets/icons/fruits/kiwi.png', 'fruits'),
  // Category('hong', 1, 'Hồng', 'assets/icons/fruits/hong.png', 'fruits'),
  // Category('dua', 1, 'Dứa', 'assets/icons/fruits/duas.png', 'fruits'),
  // Category('sung', 1, 'Sung', 'assets/icons/fruits/sung.png', 'fruits'),
  // Category(
  //     'anh-dao', 1, 'Anh đào', 'assets/icons/fruits/anh-dao.png', 'fruits'),
  // Category('quan-thoai', 1, 'Quả nho', 'assets/icons/fruits/quan-thoai.png',
  //     'fruits'),
  // Category('man', 1, 'Mận', 'assets/icons/fruits/man.png', 'fruits'),
  // Category(
  //     'dua-vang', 1, 'Dưa vàng', 'assets/icons/fruits/dua-vang.png', 'fruits'),
  // Category('le', 1, 'Lê', 'assets/icons/fruits/le.png', 'fruits'),
  // Category('nhan', 1, 'Nhãn', 'assets/icons/fruits/nhan.png', 'fruits'),
  // Category('dua', 1, 'Dừa', 'assets/icons/fruits/duaf.png', 'fruits'),
  // Category(
  //     'dua-hau', 1, 'Dưa hấu', 'assets/icons/fruits/dua-hau.png', 'fruits'),
  // Category(
  //     'dua-luoi', 1, 'Dưa lưới', 'assets/icons/fruits/dua-luoi.png', 'fruits'),
  // Category('quat', 1, 'Quất', 'assets/icons/fruits/quat.png', 'fruits'),
  // Category('ca-chua-bi', 1, 'Cà chua bi', 'assets/icons/fruits/ca-chua-bi.png',
  //     'fruits'),
  // Category(
  //     'ca-chua', 1, 'Cà chua', 'assets/icons/fruits/ca-chua.png', 'fruits'),
  // Category('chuoi', 1, 'Chuối', 'assets/icons/fruits/chuoi.png', 'fruits'),
  // Category('chanh-xanh', 1, 'Chanh xanh', 'assets/icons/fruits/chanh-xanh.png',
  //     'fruits'),
  // Category('chanh-vang', 1, 'Chanh vàng', 'assets/icons/fruits/chanh-vang.png',
  //     'fruits'),
  // Category('buoi', 1, 'Bưởi', 'assets/icons/fruits/buoi.png', 'fruits'),
];

List<Category> vegetables = [
  Category('khoai-mon', 1, 'Khoai môn', 'assets/icons/vegetables/khoai-mon.png',
      'vegetables'),
  Category('nam', 1, 'Nấm', 'assets/icons/vegetables/nam.png', 'vegetables'),
  Category('nam-kim-cham', 1, 'Nấm kim châm',
      'assets/icons/vegetables/nam-kim-cham.png', 'vegetables'),
  Category('nam-huong', 1, 'Nấm hương', 'assets/icons/vegetables/nam-huong.png',
      'vegetables'),
  Category('dau-que', 1, 'Đậu que', 'assets/icons/vegetables/dau-que.png',
      'vegetables'),
  Category('ot-chi-thien', 1, 'Ớt chỉ thiên',
      'assets/icons/vegetables/ot-chi-thien.png', 'vegetables'),
  Category('ot-chuong', 1, 'Ớt chuông', 'assets/icons/vegetables/ot-chuong.png',
      'vegetables'),
  Category('toi-tay', 1, 'Tỏi tây', 'assets/icons/vegetables/toi-tay.png',
      'vegetables'),
  Category('ot', 1, 'Ớt', 'assets/icons/vegetables/ot.png', 'vegetables'),
  Category('sup-lo-trang', 1, 'Súp lơ trắng',
      'assets/icons/vegetables/sup-lo-trang.png', 'vegetables'),
  Category('xu-hao', 1, 'Xu hào', 'assets/icons/vegetables/xu-hao.png',
      'vegetables'),
  Category('bi-ngo-vang', 1, 'Bí ngô vàng',
      'assets/icons/vegetables/bi-ngo-vang.png', 'vegetables'),
  Category('rau-diep', 1, 'Rau diếp', 'assets/icons/vegetables/rau-diep.png',
      'vegetables'),
  Category('rau-chan-vit', 1, 'Rau chân vịt',
      'assets/icons/vegetables/rau-chan-vit.png', 'vegetables'),
  Category('can-tay', 1, 'Cần tây', 'assets/icons/vegetables/can-tay.png',
      'vegetables'),
  Category('xa-lach', 1, 'Xà lách', 'assets/icons/vegetables/xa-lach.png',
      'vegetables'),
  Category('bi-xanh', 1, 'Bí xanh', 'assets/icons/vegetables/bi-xanh.png',
      'vegetables'),
  Category('nam-so', 1, 'Nấm sò', 'assets/icons/vegetables/nam-so.png',
      'vegetables'),
  Category('cai-ngot', 1, 'Cải ngọt', 'assets/icons/vegetables/cai-ngot.png',
      'vegetables'),
  Category('la-lot', 1, 'Lá lốt', 'assets/icons/vegetables/la-lot.png',
      'vegetables'),
  Category('mang-tay', 1, 'Măng tây', 'assets/icons/vegetables/mang-tay.png',
      'vegetables'),
  Category('ngo', 1, 'Ngô', 'assets/icons/vegetables/ngo.png', 'vegetables'),
  Category('nhan-sam', 1, 'Nhân sâm', 'assets/icons/vegetables/nhan-sam.png',
      'vegetables'),
  Category('khoai-tay', 1, 'Khoai tây', 'assets/icons/vegetables/khoai-tay.png',
      'vegetables'),
  Category('khoai-lang', 1, 'Khoai lang',
      'assets/icons/vegetables/khoai-lang.png', 'vegetables'),
  Category('nam-dui-ga', 1, 'Nấm đùi gà',
      'assets/icons/vegetables/nam-dui-ga.png', 'vegetables'),
  Category('he', 1, 'Hẹ', 'assets/icons/vegetables/he.png', 'vegetables'),
  Category('hanh-la', 1, 'Hành lá', 'assets/icons/vegetables/hanh-la.png',
      'vegetables'),
  Category('gia-do-xanh', 1, 'Giá đỗ xanh',
      'assets/icons/vegetables/gia-do-xanh.png', 'vegetables'),
  Category('gia-do', 1, 'Giá đỗ', 'assets/icons/vegetables/gia-do.png',
      'vegetables'),
  Category('dua-chuot', 1, 'Dưa chuột', 'assets/icons/vegetables/dua-chuot.png',
      'vegetables'),
  Category('cu-sen', 1, 'Củ sen', 'assets/icons/vegetables/cu-sen.png',
      'vegetables'),
  Category('cu-cai-duong', 1, 'Củ cải đường',
      'assets/icons/vegetables/cu-cai-duong.png', 'vegetables'),
  Category('cu-cai-trang', 1, 'Củ cải trắng',
      'assets/icons/vegetables/cu-cai-trang.png', 'vegetables'),
  Category('cu-cai', 1, 'Củ cải', 'assets/icons/vegetables/cu-cai.png',
      'vegetables'),
  Category('hanh-tay', 1, 'Hành tây', 'assets/icons/vegetables/hanh-tay.png',
      'vegetables'),
  Category('hanh-kho', 1, 'Hành khô', 'assets/icons/vegetables/hanh-kho.png',
      'vegetables'),
  Category('cai-xoan', 1, 'Cải xoăn', 'assets/icons/vegetables/cai-xoan.png',
      'vegetables'),
  Category('cai-canh', 1, 'Cải canh', 'assets/icons/vegetables/cai-canh.png',
      'vegetables'),
  Category('xa-lach-dai', 1, 'Xà lách dài',
      'assets/icons/vegetables/xa-lach-dai.png', 'vegetables'),
  Category('cai-be-xanh', 1, 'Cải bẹ xanh',
      'assets/icons/vegetables/cai-be-xanh.png', 'vegetables'),
  Category('mang', 1, 'Măng', 'assets/icons/vegetables/mang.png', 'vegetables'),
  Category('bap-cai', 1, 'Bắp cải', 'assets/icons/vegetables/bap-cai.png',
      'vegetables'),
  Category('cai-thao', 1, 'Cải thảo', 'assets/icons/vegetables/cai-thao.png',
      'vegetables'),
  Category('ca-rot', 1, 'Cà rốt', 'assets/icons/vegetables/ca-rot.png',
      'vegetables'),
  Category('ca-tim-dai', 1, 'Cà tím dài',
      'assets/icons/vegetables/ca-tim-dai.png', 'vegetables'),
  Category('cu-cai-tim', 1, 'Củ cải tím',
      'assets/icons/vegetables/cu-cai-tim.png', 'vegetables'),
  Category('sup-lo', 1, 'Súp lơ', 'assets/icons/vegetables/sup-lo.png',
      'vegetables'),
  Category('bi-ngo', 1, 'Bí ngô', 'assets/icons/vegetables/bi-ngo.png',
      'vegetables'),
  Category(
      'bi-do', 1, 'Bí đỏ', 'assets/icons/vegetables/bi-do.png', 'vegetables'),
  Category('cai-chip', 1, 'Cải chíp', 'assets/icons/vegetables/cai-chip.png',
      'vegetables'),
];

List<Category> meats = [
  Category(
      'bung-heo', 1, 'Bụng heo', 'assets/icons/meats/bung-heo.png', 'meats'),
  Category('canh-ga', 1, 'Cánh gà', 'assets/icons/meats/canh-ga.png', 'meats'),
  Category(
      'chan-gio', 1, 'Chân giò', 'assets/icons/meats/chan-gio.png', 'meats'),
  Category('dui-ga', 1, 'Đùi gà', 'assets/icons/meats/dui-ga.png', 'meats'),
  Category('ga', 1, 'Gà', 'assets/icons/meats/ga.png', 'meats'),
  Category('ga-tay', 1, 'Gà tây', 'assets/icons/meats/ga-tay.png', 'meats'),
  Category(
      'giam-bong', 1, 'Giăm bông', 'assets/icons/meats/giam-bong.png', 'meats'),
  Category(
      'gio-tuoi', 1, 'Giò tươi', 'assets/icons/meats/gio-tuoi.png', 'meats'),
  Category('jamon', 1, 'Jamon', 'assets/icons/meats/jamon.png', 'meats'),
  Category(
      'mat-suon', 1, 'Mắt sườn', 'assets/icons/meats/mat-suon.png', 'meats'),
  Category('prosciutto', 1, 'Prosciutto', 'assets/icons/meats/prosciutto.png',
      'meats'),
  Category(
      'thit-than', 1, 'Thịt thăn', 'assets/icons/meats/thit-than.png', 'meats'),
  Category('thit-ba-roi', 1, 'Thịt ba rọi',
      'assets/icons/meats/thit-ba-roi.png', 'meats'),
  Category('thit-bo', 1, 'Thịt bò', 'assets/icons/meats/thit-bo.png', 'meats'),
  Category(
      'thit-cuu', 1, 'Thịt cừu', 'assets/icons/meats/thit-cuu.png', 'meats'),
  Category(
      'thit-heo', 1, 'Thịt heo', 'assets/icons/meats/thit-heo.png', 'meats'),
  Category(
      'tomahawk', 1, 'Tomahawk', 'assets/icons/meats/tomahawk.png', 'meats'),
  Category('trung', 1, 'Trứng', 'assets/icons/meats/trung.png', 'meats'),
  Category(
      'trung-cut', 1, 'Trứng cút', 'assets/icons/meats/trung-cut.png', 'meats'),
  Category('uc-ga', 1, 'Ức gà', 'assets/icons/meats/uc-ga.png', 'meats'),
  Category('vit', 1, 'Vịt', 'assets/icons/meats/vit.png', 'meats'),
  Category(
      'xuc-xich', 1, 'Xúc xích', 'assets/icons/meats/xuc-xich.png', 'meats'),
  Category('xuc-xich-cay', 1, 'Xúc xích cay',
      'assets/icons/meats/xuc-xich-cay.png', 'meats'),
  Category('xuc-xich-hun-khoi', 1, 'Xúc xích hun khói',
      'assets/icons/meats/xuc-xich-hun-khoi.png', 'meats'),
  Category('xuc-xich-y', 1, 'Xúc xích Ý', 'assets/icons/meats/xuc-xich-y.png',
      'meats'),
  Category('xuong-chu-T', 1, 'Xương chữ T',
      'assets/icons/meats/xuong-chu-t.png', 'meats'),
  Category('xuong-suon', 1, 'Xương sườn', 'assets/icons/meats/xuong-suon.png',
      'meats'),
];

List<Category> seafood = [
  Category('oc', 1, 'Ốc', 'assets/icons/seafood/oc.png', 'seafood'),
  Category('tom-su', 1, 'Tôm sú', 'assets/icons/seafood/tom-su.png', 'seafood'),
  Category(
      'tom-hum', 1, 'Tôm hùm', 'assets/icons/seafood/tom-hum.png', 'seafood'),
  Category('trung-ca-muoi', 1, 'Trứng cá muối',
      'assets/icons/seafood/trung-ca-muoi.png', 'seafood'),
  Category('ngao', 1, 'Ngao', 'assets/icons/seafood/ngao.png', 'seafood'),
  Category('nhim-bien', 1, 'Nhím biển', 'assets/icons/seafood/nhim-bien.png',
      'seafood'),
  Category('rong-bien', 1, 'Rong biển', 'assets/icons/seafood/rong-bien.png',
      'seafood'),
  Category('so-huyet', 1, 'Sò huyết', 'assets/icons/seafood/so-huyet.png',
      'seafood'),
  Category('trung-ca', 1, 'Trứng cá', 'assets/icons/seafood/trung-ca.png',
      'seafood'),
  Category(
      'muc-ong', 1, 'Mực ống', 'assets/icons/seafood/muc-ong.png', 'seafood'),
  Category('muc-nang', 1, 'Mực nang', 'assets/icons/seafood/muc-nang.png',
      'seafood'),
  Category(
      'hai-sam', 1, 'Hải sâm', 'assets/icons/seafood/hai-sam.png', 'seafood'),
  Category('ca-tuyet', 1, 'Cá tuyết', 'assets/icons/seafood/ca-tuyet.png',
      'seafood'),
  Category('ca-thu', 1, 'Cá thu', 'assets/icons/seafood/ca-thu.png', 'seafood'),
  Category('ca-hoi', 1, 'Cá hồi', 'assets/icons/seafood/ca-hoi.png', 'seafood'),
  Category('ca-kho', 1, 'Cá khô', 'assets/icons/seafood/ca-kho.png', 'seafood'),
  Category('ca-meo', 1, 'Cá mèo', 'assets/icons/seafood/ca-meo.png', 'seafood'),
  Category('ca-moi', 1, 'Cá mòi', 'assets/icons/seafood/ca-moi.png', 'seafood'),
  Category('ca-ngu', 1, 'Cá ngừ', 'assets/icons/seafood/ca-ngu.png', 'seafood'),
  Category('ca-ho', 1, 'Cá hố', 'assets/icons/seafood/ca-ho.png', 'seafood'),
  Category('ca-com', 1, 'Cá cơm', 'assets/icons/seafood/ca-com.png', 'seafood'),
  Category('ca-chinh', 1, 'Cá chình', 'assets/icons/seafood/ca-chinh.png',
      'seafood'),
  Category('ca', 1, 'Cá', 'assets/icons/seafood/ca.png', 'seafood'),
  Category('cua-tuyet', 1, 'Cua tuyết', 'assets/icons/seafood/cua-tuyet.png',
      'seafood'),
  Category('sua', 1, 'Sứa', 'assets/icons/seafood/sua.png', 'seafood'),
  Category('trai', 1, 'Trai', 'assets/icons/seafood/trai.png', 'seafood'),
  Category('tep', 1, 'Tép', 'assets/icons/seafood/tep.png', 'seafood'),
  Category('bach-tuoc', 1, 'Bạch tuộc', 'assets/icons/seafood/bach-tuoc.png',
      'seafood'),
  Category('cua', 1, 'Cua', 'assets/icons/seafood/cua.png', 'seafood'),
  Category('hen', 1, 'Hến', 'assets/icons/seafood/hen.png', 'seafood'),
  Category('hau', 1, 'Hàu', 'assets/icons/seafood/hau.png', 'seafood'),
  Category(
      'bao-ngu', 1, 'Bào ngư', 'assets/icons/seafood/bao-ngu.png', 'seafood'),
  Category('so', 1, 'Sò', 'assets/icons/seafood/so.png', 'seafood'),
];

List<Category> dishes = [
  Category(
      'mon-ham', 1, 'Món hầm', 'assets/icons/dishes/mon-ham.png', 'dishes'),
  Category('garu', 1, 'Garu', 'assets/icons/dishes/garu.png', 'dishes'),
  Category('mi-ong', 1, 'Mì ống', 'assets/icons/dishes/mi-ong.png', 'dishes'),
  Category('com-rong-bien', 1, 'Onigiri',
      'assets/icons/dishes/com-rong-bien.png', 'dishes'),
  Category('cha-ca-han-quoc', 1, 'Chả cá Hàn Quốc',
      'assets/icons/dishes/cha-ca-han-quoc.png', 'dishes'),
  Category('nuoc-dung', 1, 'Nước dùng', 'assets/icons/dishes/nuoc-dung.png',
      'dishes'),
  Category('nori', 1, 'Nori', 'assets/icons/dishes/nori.png', 'dishes'),
  Category(
      'ngu-coc', 1, 'Ngũ cốc', 'assets/icons/dishes/ngu-coc.png', 'dishes'),
  Category(
      'pad-thai', 1, 'Pad Thái', 'assets/icons/dishes/pad-thai.png', 'dishes'),
  Category('chao-hai-san', 1, 'Cháo hải sản',
      'assets/icons/dishes/chao-hai-san.png', 'dishes'),
  Category('pho', 1, 'Phở', 'assets/icons/dishes/pho.png', 'dishes'),
  Category('pizza', 1, 'Pizza', 'assets/icons/dishes/pizza.png', 'dishes'),
  Category(
      'pulkogi', 1, 'Pulkogi', 'assets/icons/dishes/pulkogi.png', 'dishes'),
  Category('thit-nuong', 1, 'Thịt nướng', 'assets/icons/dishes/thit-nuong.png',
      'dishes'),
  Category(
      'sashimi', 1, 'Sashimi', 'assets/icons/dishes/sashimi.png', 'dishes'),
  Category(
      'rendang', 1, 'Rendang', 'assets/icons/dishes/rendang.png', 'dishes'),
  Category('banh-ngot', 1, 'Bánh ngọt', 'assets/icons/dishes/banh-ngot.png',
      'dishes'),
  Category('salad', 1, 'Salad', 'assets/icons/dishes/salad.png', 'dishes'),
  Category('lap-xuong', 1, 'Lạp xưởng', 'assets/icons/dishes/lap-xuong.png',
      'dishes'),
  Category('mi-goi', 1, 'Mì gói', 'assets/icons/dishes/mi-goi.png', 'dishes'),
  Category(
      'mi-nuong', 1, 'Mì nướng', 'assets/icons/dishes/mi-nuong.png', 'dishes'),
  Category(
      'mi-tron', 1, 'Mì trộn', 'assets/icons/dishes/mi-tron.png', 'dishes'),
  Category(
      'mi-udon', 1, 'Mì udon', 'assets/icons/dishes/mi-udon.png', 'dishes'),
  Category(
      'kim-chi', 1, 'Kim chi', 'assets/icons/dishes/kim-chi.png', 'dishes'),
  Category('kebab', 1, 'Kebab', 'assets/icons/dishes/kebab.png', 'dishes'),
  Category('hang-dong-lanh', 1, 'Hàng đông lạnh',
      'assets/icons/dishes/hang-dong-lanh.png', 'dishes'),
  Category(
      'goi-cuon', 1, 'Gỏi cuốn', 'assets/icons/dishes/goi-cuon.png', 'dishes'),
  Category('gimbap', 1, 'Gimbap', 'assets/icons/dishes/gimbap.png', 'dishes'),
  Category(
      'gnocchi', 1, 'Gnocchi', 'assets/icons/dishes/gnocchi.png', 'dishes'),
  Category('ga-ran', 1, 'Gà rán', 'assets/icons/dishes/ga-ran.png', 'dishes'),
  Category('dua-chuot-muoi', 1, 'Dưa chuột muối',
      'assets/icons/dishes/dua-chuot-muoi.png', 'dishes'),
  Category('com-trang', 1, 'Cơm trắng', 'assets/icons/dishes/com-trang.png',
      'dishes'),
  Category(
      'com-rang', 1, 'Cơm rang', 'assets/icons/dishes/com-rang.png', 'dishes'),
  Category('ca-hop', 1, 'Cá hộp', 'assets/icons/dishes/ca-hop.png', 'dishes'),
  Category('ca-ri', 1, 'Cà ri', 'assets/icons/dishes/ca-ri.png', 'dishes'),
  Category('banh-mi-kep-xuc-xich', 1, 'Bánh mì kẹp xúc xích',
      'assets/icons/dishes/banh-mi-kep-xuc-xich.png', 'dishes'),
  Category('banh-mi-sandwich', 1, 'Bánh mì sandwich',
      'assets/icons/dishes/banh-mi-sandwich.png', 'dishes'),
  Category(
      'banh-goi', 1, 'Bánh gối', 'assets/icons/dishes/banh-goi.png', 'dishes'),
  Category('hamburger', 1, 'Hamburger', 'assets/icons/dishes/hamburger.png',
      'dishes'),
  Category('canh', 1, 'Canh', 'assets/icons/dishes/canh.png', 'dishes'),
  Category('chao', 1, 'Cháo', 'assets/icons/dishes/chao.png', 'dishes'),
  Category(
      'banh-mi', 1, 'Bánh mì', 'assets/icons/dishes/banh-mi.png', 'dishes'),
  Category(
      'banh-bao', 1, 'Bánh bao', 'assets/icons/dishes/banh-bao.png', 'dishes'),
  Category(
      'nem-ran', 1, 'Nem rán', 'assets/icons/dishes/nem-ran.png', 'dishes'),
  Category(
      'com-tron', 1, 'Cơm trộn', 'assets/icons/dishes/com-tron.png', 'dishes'),
];

List<Category> dairyProducts = [
  Category('roquefort', 1, 'Roquefort',
      'assets/icons/dairy_products/roquefort.png', 'dairy_products'),
  Category('sua-hanh-nhan', 1, 'Sữa hạnh nhân',
      'assets/icons/dairy_products/sua-hanh-nhan.png', 'dairy_products'),
  Category('sua-dau-nanh', 1, 'Sữa đậu nành',
      'assets/icons/dairy_products/sua-dau-nanh.png', 'dairy_products'),
  Category('thuc-uong-loi-khuan', 1, 'Thức uống lợi khuẩn',
      'assets/icons/dairy_products/thuc-uong-loi-khuan.png', 'dairy_products'),
  Category('tra-sua', 1, 'Trà sữa', 'assets/icons/dairy_products/tra-sua.png',
      'dairy_products'),
  Category('sua-dua', 1, 'Sữa dừa', 'assets/icons/dairy_products/sua-dua.png',
      'dairy_products'),
  Category('sua-chua', 1, 'Sữa chua',
      'assets/icons/dairy_products/sua-chua.png', 'dairy_products'),
  Category('sua-bot', 1, 'Sữa bột', 'assets/icons/dairy_products/sua-bot.png',
      'dairy_products'),
  Category('sua-tuoi', 1, 'Sữa tươi',
      'assets/icons/dairy_products/sua-tuoi.png', 'dairy_products'),
  Category('pho-mat-kem', 1, 'Phô mát kem',
      'assets/icons/dairy_products/pho-mat-kem.png', 'dairy_products'),
  Category('pho-mai', 1, 'Phô mai', 'assets/icons/dairy_products/pho-mai.png',
      'dairy_products'),
  Category('pho-mai-mozzarella', 1, 'Phô mai mozzarella',
      'assets/icons/dairy_products/pho-mai-mozzarella.png', 'dairy_products'),
  Category('ricotta', 1, 'Ricotta', 'assets/icons/dairy_products/ricotta.png',
      'dairy_products'),
  Category('kem-tuoi', 1, 'Kem tươi',
      'assets/icons/dairy_products/kem-tuoi.png', 'dairy_products'),
  Category('kem-chua', 1, 'Kem chua',
      'assets/icons/dairy_products/kem-chua.png', 'dairy_products'),
  Category('gouda', 1, 'Gouda', 'assets/icons/dairy_products/gouda.png',
      'dairy_products'),
  Category('cheddar', 1, 'Cheddar', 'assets/icons/dairy_products/cheddar.png',
      'dairy_products'),
  Category(
      'bo', 1, 'Bơ', 'assets/icons/dairy_products/bo.png', 'dairy_products'),
];

List<Category> drinks = [];
List<Category> alcohol = [];
List<Category> sauces = [];
List<Category> spices = [];
List<Category> bread = [];
List<Category> desserts = [];
List<Category> nuts = [];
List<Category> cereals = [];
List<Category> etc = [];

List<Food> foods = [
  Food(fruits, 'fruits', 'Trái cây', 'assets/icons/fruits/fruits.png'),
  Food(meats, 'meats', 'Thịt', 'assets/icons/meats/meats.png'),
  Food(vegetables, 'vegetables', 'Rau',
      'assets/icons/vegetables/vegetables.png'),
  Food(dairyProducts, 'dairy_products', 'Sản phẩm từ sữa',
      'assets/icons/dairy_products/dairy_products.png'),
  Food(dishes, 'dishes', 'Món ăn', 'assets/icons/dishes/dishes.png'),
  Food(seafood, 'seafood', 'Hải sản', 'assets/icons/seafood/seafood.png'),
  Food(drinks, 'drinks', 'Đồ uống', 'assets/icons/drinks/drinks.png'),
  Food(alcohol, 'alcohol', 'Rượu', 'assets/icons/alcohol/alcohol.png'),
  Food(sauces, 'sauces', 'Nước xốt', 'assets/icons/sauces/sauces.png'),
  Food(spices, 'spices', 'Gia vị', 'assets/icons/spices/spices.png'),
  Food(bread, 'bread', 'Bánh mì', 'assets/icons/bread/bread.png'),
  Food(desserts, 'desserts', 'Tráng miệng',
      'assets/icons/desserts/desserts.png'),
  Food(nuts, 'nuts', 'Quả hạch', 'assets/icons/nuts/nuts.png'),
  Food(cereals, 'cereals', 'Ngũ cốc', 'assets/icons/cereals/cereals.png'),
  Food(etc, 'etc', 'Vân vân.', 'assets/icons/etc/etc.png'),
];
