// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTIWyWAQojsbHTGKLSoBMU-rBGxum6UAY',
    appId: '1:356005686753:web:fbfebe041dd705946c76a0',
    messagingSenderId: '356005686753',
    projectId: 'fsn-project-420204',
    authDomain: 'fsn-project-420204.firebaseapp.com',
    storageBucket: 'fsn-project-420204.appspot.com',
    measurementId: 'G-5J2M5WBQ48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnRcQzqhkTSM5Sb9HeJ6IOV4fijltc8W4',
    appId: '1:356005686753:android:9e7b366282b64d796c76a0',
    messagingSenderId: '356005686753',
    projectId: 'fsn-project-420204',
    storageBucket: 'fsn-project-420204.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBytfY-_7OJfBiJrbUEB4ZyJvM9a6Cob7A',
    appId: '1:356005686753:ios:3f7bd9bbc37525376c76a0',
    messagingSenderId: '356005686753',
    projectId: 'fsn-project-420204',
    storageBucket: 'fsn-project-420204.appspot.com',
    androidClientId: '356005686753-5o9ne1ni1kfugf1b7catolggucqm0713.apps.googleusercontent.com',
    iosClientId: '356005686753-jo29smg960b8v42aiemdp8fd1bra0plb.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBytfY-_7OJfBiJrbUEB4ZyJvM9a6Cob7A',
    appId: '1:356005686753:ios:3f7bd9bbc37525376c76a0',
    messagingSenderId: '356005686753',
    projectId: 'fsn-project-420204',
    storageBucket: 'fsn-project-420204.appspot.com',
    androidClientId: '356005686753-5o9ne1ni1kfugf1b7catolggucqm0713.apps.googleusercontent.com',
    iosClientId: '356005686753-jo29smg960b8v42aiemdp8fd1bra0plb.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTIWyWAQojsbHTGKLSoBMU-rBGxum6UAY',
    appId: '1:356005686753:web:0d7f1a3a535b43576c76a0',
    messagingSenderId: '356005686753',
    projectId: 'fsn-project-420204',
    authDomain: 'fsn-project-420204.firebaseapp.com',
    storageBucket: 'fsn-project-420204.appspot.com',
    measurementId: 'G-0ZD8DZR6W7',
  );
}
